INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (1, 'S3');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (2, 'DDB');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (3, 'VPC');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (4, 'RDS');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (5, 'RS');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (6, 'EC2');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (7, 'ELB');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (8, 'ALB');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (9, 'ECC');
INSERT INTO RESOURCE_CATEGORY( ID, NAME) VALUES (10, 'ESS');



INSERT INTO RESOURCE(ID, CAT_ID, NAME, REGION, STATUS, RESOURCE_ID, TYPE, IMAGE_ID, VPC_ID, SUBNET_ID, ENDPOINT, RELATED_RESOURCES) VALUES (SEQ_RESOURCE.NEXTVAL, 1, 'NoName', 'ap-northeast-2', 'running', 'i-06d8abf5ff6656f94', 't2.nano', 'ami-9bec36f5', 'vpc-001afb69', 'subnet-49b55420', '2017-10-26T04:18:57.000Z', 6);
INSERT INTO RESOURCE(ID, CAT_ID, NAME, REGION, STATUS, RESOURCE_ID, TYPE, IMAGE_ID, VPC_ID, SUBNET_ID, ENDPOINT, RELATED_RESOURCES) VALUES (SEQ_RESOURCE.NEXTVAL, 1, 'TwoName', 'ap-northeast-2', 'running', 'i-06d8abf5ff6656f93', 't2.nano', 'ami-9bec36f5','vpc-001afb69', 'subnet-49b55420', '2017-10-26T04:18:57.000Z', 6);
