
#server
#server.port=8080


spring:
  profiles:
    active: "dev"

# logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    :org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql=trace
  level.: info
---

spring:
  profiles: dev

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import.sql
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /myconsole
      enabled: true

---

spring:
  profiles: staging

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import.sql
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /myconsole
      enabled: true

---

spring:
  profiles: uat

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import.sql
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /myconsole
      enabled: true

---

spring:
  profiles: loadtest

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import.sql
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /myconsole
      enabled: true

---

spring:
  profiles: production

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialize: true
    schema: classpath:schema.sql
    data: classpath:import.sql
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /myconsole
      enabled: true

---

